ROOT=	../../..

OBJS=	test.o
TARGET=	$(BIN)/test.exe
LIBS=	$(LIB)/crt0.o $(LIB)/libc_s.lib $(LIB)/libsys.lib
#LDFLAGS=-lgcc -L/lib/gcc-lib/i686-pc-cygwin/3.2

include $(ROOT)/coreos/make.conf
include $(ROOT)/coreos/make.actions
