ROOT=	../../../..
TARGET_D=	$(BIN)/es1371.kll
OBJS=	es1371.o
BASE=	es1371
LIBS=	$(LIB)/pci.lib $(LIB)/kernel.lib $(LIB)/sound.lib
DEFINES=-DKERNEL

include $(ROOT)/coreos/make.conf
include $(ROOT)/coreos/make.actions
