#! /bin/sh -x
# testmalloc tests some unusual cases -- will test all branches in free,
# which is important.
./testmalloc$EXT $@
# simumalloc makes a good thorough exercise for malloc and free.
# need something for realloc, though.
./simumalloc$EXT -d -t 2000 -s 1024 -l 2000 $@
./simumalloc$EXT -t 15000 -s 1024 -l 2000 $@
./simumalloc$EXT -d -t 5000 -s 512 -l 20 $@
./simumalloc$EXT -T trace$EXT -t 5000 -s 512 -l 20 $@
./simumalloc$EXT -d -t 500 -s 512 -l 20 $@
./simumalloc$EXT -d -t 500 -s 512 -l 500 $@
./simumalloc$EXT -d -t 500 -s 512 -a $@
