# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1997 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details

OBJS=	regcomp.o regerror.o regexec.o regfree.o
TARGET_S=libregex.lib

include ../../make.conf
include ../../make.actions
