OBJS=	src/base/ftsystem.o \
	src/base/ftinit.o \
	src/base/ftdebug.o \
	src/base/ftbase.o \
	src/base/ftglyph.o \
	src/base/ftbbox.o \
	src/base/ftmm.o \
	src/winfonts/winfnt.o \
	src/truetype/truetype.o src/sfnt/sfnt.o src/psnames/psnames.o \
	src/autohint/autohint.o src/cache/ftcache.o \
	src/raster/raster.o src/smooth/smooth.o
TARGET_S=	../freetype_s.lib
#TARGET_D=	$(BIN)/freetype.dll
#IMP=	$(LIB)/freetype.lib
#BASE=	freetype
#DEF=	freetype.def
#LIBS=	$(LIB)/libc.lib

include ../../make.conf
include ../../make.actions
