all:
	make -C client
	make -C hello
	make -C nasm
	make -C shell
	make -C tetris
	make -C test
	make -C thrtest
	make -C vidtest

clean:
	make -C client clean
	make -C hello clean
	make -C nasm clean
	make -C shell clean
	make -C tetris clean
	make -C test clean
	make -C thrtest clean
	make -C vidtest clean

