ROOT=	../../../..
TARGET_D=	$(BIN)/s3.kll
OBJS=	s3.o
BASE=	s3
LIBS=	$(LIB)/kernel.lib $(LIB)/video.lib
DEFINES=-DKERNEL -I../include

include $(ROOT)/coreos/make.conf
include $(ROOT)/coreos/make.actions
