ROOT=	../..
OBJS=	console.o
TARGET=	$(BIN)/console.exe
LIBS=	$(LIB)/framebuf_user.lib $(LIB)/freetype.lib $(LIB)/libc.lib $(LIB)/libsys.lib 

include $(ROOT)/coreos/make.conf
include $(ROOT)/coreos/make.actions
