ROOT=	../..

OBJS=	server.o console.o multibyte.o
TARGET=	$(BIN)/gconsole.exe
LIBS=	$(LIB)/crt0.o $(LIB)/gui.lib $(LIB)/libc.lib $(LIB)/libsys.lib
CFLAGS=-I../include

include $(ROOT)/coreos/make.conf
include $(ROOT)/coreos/make.actions
