ROOT=	../../..

TARGET=	$(BIN)/thrtest.exe
OBJS=	thrtest.o
LIBS=	$(LIB)/crt0.o $(LIB)/framebuf_user.lib $(LIB)/freetype.lib $(LIB)/libc.lib $(LIB)/libsys.lib

include $(ROOT)/coreos/make.conf
include $(ROOT)/coreos/make.actions
