/* Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details */
ERRNO(00, "No Error")
ERRNO(01, "Input to function out of range (EDOM)")
ERRNO(02, "Invalid multibyte sequence (EILSEQ)")
ERRNO(03, "Output of function out of range (ERANGE)")
ERRNO(04, "Command not implemented (ENOTIMPL)")
ERRNO(05, "Invalid buffer (EBUFFER)")
ERRNO(06, "File not found (ENOTFOUND)")
ERRNO(07, "Invalid argument (EINVALID)")
ERRNO(08, "Too many open files (EMFILE)")
ERRNO(09, "Out of memory (ENOMEM)")
ERRNO(10, "Invalid handle (EHANDLE)")
ERRNO(11, "Hardware fault (EHARDWARE)")
ERRNO(12, "Access denied (EACCESS)")
ERRNO(13, "End of file reached (EEOF)")
ERRNO(14, "Argument list too long (E2BIG)")
ERRNO(15, "Not a directory (ENOTADIR)")
ERRNO(16, "Software fault (EFAULT)")
ERRNO(17, "No client connected (ENOCLIENT)")
ERRNO(18, "xxx -- ENOEXEC")
ERRNO(19, "Operation was cancelled (ECANCELLED)")
ERRNO(20, "Other end of the pipe was closed (EPIPECLOSED)")
