COUNTERS_BEGIN()
COUNTER(mem_allocs,			L"Page allocations")
COUNTER(mem_frees,			L"Page frees")
COUNTER(mem_zeroes,			L"Page zeroes")
COUNTER(mem_temp_hits,		L"Temporary mapping cache hits")
COUNTER(mem_temp_misses,	L"Temporary mapping cache misses")
COUNTER(mem_pamap_quick,	L"Single-page page array maps")
COUNTER(mem_pamap_slow,		L"Multiple-page page array maps")
COUNTERS_END()
